import type { ThemeColors } from "@shared/theme";

export function createHomeGroupsStyles(colors: ThemeColors) {
  return {
    groupSectionWrap: {
      marginTop: 2,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 12,
      paddingVertical: 12,
      gap: 10,
    },
    groupSectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    groupSectionTitle: {
      color: colors.textPrimary,
      fontSize: 22,
      lineHeight: 28,
    },
    groupSectionAction: {
      color: colors.accentText,
      fontSize: 13,
      lineHeight: 18,
    },
    groupLoaderCard: {
      minHeight: 72,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceSecondary,
      paddingHorizontal: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    groupLoaderText: {
      color: colors.textSecondary,
      fontSize: 13,
      lineHeight: 18,
    },
    groupEmptyCard: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceSecondary,
      paddingHorizontal: 12,
      paddingVertical: 10,
      gap: 7,
    },
    groupEmptyTitle: {
      color: colors.textPrimary,
      fontSize: 16,
      lineHeight: 21,
    },
    groupEmptySubtitle: {
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 17,
    },
    groupEmptyActionButton: {
      alignSelf: "flex-start",
      minHeight: 32,
      borderRadius: 9,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    groupEmptyActionText: {
      color: colors.textPrimary,
      fontSize: 12,
      lineHeight: 16,
    },
    groupListWrap: {
      gap: 8,
    },
    groupCard: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceSecondary,
      paddingHorizontal: 10,
      paddingVertical: 10,
      gap: 8,
    },
    groupCardHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    groupIconWrap: {
      width: 34,
      height: 34,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
    },
    groupIdentityWrap: {
      flex: 1,
    },
    groupName: {
      color: colors.textPrimary,
      fontSize: 16,
      lineHeight: 21,
    },
    groupDescription: {
      marginTop: 1,
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 16,
    },
    groupMetaRow: {
      flexDirection: "row",
      alignItems: "center",
      flexWrap: "wrap",
      gap: 6,
    },
    groupMetaChip: {
      minHeight: 28,
      borderRadius: 9,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 8,
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
    },
    groupMetaText: {
      color: colors.textPrimary,
      fontSize: 11,
      lineHeight: 15,
    },
    groupProgressRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 8,
    },
    groupProgressCaption: {
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 16,
    },
    groupProgressPercent: {
      color: colors.textPrimary,
      fontSize: 12,
      lineHeight: 16,
    },
    groupProgressTrack: {
      width: "100%",
      height: 8,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      overflow: "hidden",
    },
    groupProgressFill: {
      height: "100%",
      borderRadius: 999,
      backgroundColor: colors.accentPrimary,
    },
    groupProgressFillDone: {
      backgroundColor: colors.successText,
    },
    groupHint: {
      color: colors.textMuted,
      fontSize: 11,
      lineHeight: 15,
    },
  } as const;
}
