import { StyleSheet } from "react-native";

import type { ThemeColors } from "@shared/theme";

export function createHomeHabitsStyles(colors: ThemeColors) {
  return {
    sectionHeader: {
      marginTop: 12,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    sectionTitle: {
      color: colors.textPrimary,
      fontSize: 34,
      lineHeight: 40,
    },
    sectionAction: {
      color: colors.accentText,
      fontSize: 15,
      lineHeight: 20,
    },
    errorBanner: {
      borderWidth: 1,
      borderColor: colors.errorBorder,
      backgroundColor: colors.errorSurface,
      borderRadius: 14,
      paddingHorizontal: 12,
      paddingVertical: 10,
      gap: 8,
    },
    errorBannerText: {
      color: colors.errorText,
      fontSize: 14,
      lineHeight: 20,
    },
    retryButton: {
      alignSelf: "flex-start",
      minHeight: 34,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.errorBorder,
      backgroundColor: colors.surface,
      paddingHorizontal: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    retryButtonText: {
      color: colors.errorText,
      fontSize: 12,
      lineHeight: 16,
    },
    loaderCard: {
      minHeight: 170,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
    },
    loaderText: {
      color: colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
    },
    emptyCard: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 16,
      paddingVertical: 16,
      gap: 10,
    },
    emptyTitle: {
      color: colors.textPrimary,
      fontSize: 24,
      lineHeight: 30,
    },
    emptySubtitle: {
      color: colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
    },
    emptyActionButton: {
      minHeight: 42,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceSecondary,
      alignSelf: "flex-start",
      paddingHorizontal: 14,
      alignItems: "center",
      justifyContent: "center",
    },
    emptyActionText: {
      color: colors.textPrimary,
      fontSize: 14,
      lineHeight: 18,
    },
    listWrap: {
      gap: 12,
    },
    habitCard: {
      position: "relative",
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 12,
      paddingVertical: 12,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      shadowColor: colors.cardShadow,
      shadowOffset: {
        width: 0,
        height: 8,
      },
      shadowOpacity: 0.18,
      shadowRadius: 14,
      elevation: 4,
    },
    habitCardGlow: {
      ...StyleSheet.absoluteFillObject,
      borderRadius: 18,
      backgroundColor: colors.successSurface,
      opacity: 0,
    },
    habitMainPress: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    habitIconWrap: {
      width: 56,
      height: 56,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceSecondary,
      alignItems: "center",
      justifyContent: "center",
    },
    habitIdentityWrap: {
      flex: 1,
      gap: 3,
    },
    habitName: {
      color: colors.textPrimary,
      fontSize: 20,
      lineHeight: 26,
    },
    streakWrap: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    streakText: {
      color: colors.textSecondary,
      fontSize: 14,
      lineHeight: 18,
    },
    habitGoalText: {
      color: colors.textMuted,
      fontSize: 12,
      lineHeight: 16,
    },
    completeCircle: {
      width: 56,
      height: 56,
      borderRadius: 28,
      borderWidth: 2,
      borderColor: colors.border,
      backgroundColor: colors.surfaceSecondary,
      alignItems: "center",
      justifyContent: "center",
    },
    completeCircleDone: {
      borderColor: colors.successBorder,
      backgroundColor: colors.successSurface,
    },
  } as const;
}
