import type { ThemeColors } from "@shared/theme";

export function createHomeProgressStyles(colors: ThemeColors) {
  return {
    progressCard: {
      marginTop: 4,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 16,
      paddingVertical: 16,
      gap: 12,
      shadowColor: colors.cardShadow,
      shadowOffset: {
        width: 0,
        height: 8,
      },
      shadowOpacity: 0.2,
      shadowRadius: 16,
      elevation: 6,
    },
    progressHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    progressTitle: {
      color: colors.textPrimary,
      fontSize: 34,
      lineHeight: 40,
    },
    progressMeta: {
      marginTop: 4,
      color: colors.textSecondary,
      fontSize: 15,
      lineHeight: 21,
    },
    progressIconWrap: {
      position: "relative",
      width: 50,
      height: 50,
      borderRadius: 25,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceSecondary,
      alignItems: "center",
      justifyContent: "center",
      overflow: "visible",
    },
    progressIconAuraOuter: {
      position: "absolute",
      top: -4,
      left: -4,
      right: -4,
      bottom: -4,
      borderRadius: 27,
      backgroundColor: "#F3A73B14",
      shadowColor: "#F3A73B",
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowOpacity: 0.28,
      shadowRadius: 9,
      elevation: 5,
      opacity: 0,
    },
    progressIconAuraInner: {
      position: "absolute",
      top: 8,
      left: 8,
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: "#F3A73B24",
      opacity: 0,
    },
    progressStatusRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    progressMessage: {
      color: colors.textSecondary,
      fontSize: 15,
      lineHeight: 20,
      flex: 1,
    },
    progressPercent: {
      color: colors.textPrimary,
      fontSize: 15,
      lineHeight: 20,
    },
    progressTrack: {
      height: 14,
      width: "100%",
      borderRadius: 999,
      overflow: "hidden",
      backgroundColor: colors.surfaceSecondary,
      borderWidth: 1,
      borderColor: colors.border,
    },
    progressFill: {
      height: "100%",
      borderRadius: 999,
      backgroundColor: colors.accentPrimary,
      width: 0,
    },
  } as const;
}
