import type { ThemeColors } from "@shared/theme";

export function createStatsDayDetailsStyles(colors: ThemeColors) {
  return {
    dayDetailsCard: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 12,
      paddingVertical: 12,
      gap: 10,
    },
    dayDetailsHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 8,
    },
    dayDetailsHeaderTextWrap: {
      flex: 1,
    },
    dayDetailsTitle: {
      color: colors.textPrimary,
      fontSize: 20,
      lineHeight: 25,
    },
    dayDetailsSubtitle: {
      marginTop: 3,
      color: colors.textSecondary,
      fontSize: 13,
      lineHeight: 18,
    },
    filtersRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    filterButton: {
      flex: 1,
      minHeight: 34,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceSecondary,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 8,
    },
    filterButtonActive: {
      borderColor: colors.accentText,
      backgroundColor: colors.accentSecondary,
    },
    filterButtonText: {
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 16,
    },
    filterButtonTextActive: {
      color: colors.textPrimary,
    },
    filterHintText: {
      color: colors.textMuted,
      fontSize: 12,
      lineHeight: 16,
    },
    sectionBlock: {
      gap: 6,
      marginTop: 4,
    },
    sectionTitle: {
      color: colors.textPrimary,
      fontSize: 15,
      lineHeight: 20,
    },
    rowsList: {
      gap: 8,
    },
    activityRow: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceSecondary,
      minHeight: 52,
      paddingHorizontal: 10,
      paddingVertical: 8,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    activityIconWrap: {
      width: 32,
      height: 32,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
    },
    activityIdentity: {
      flex: 1,
      gap: 1,
    },
    activityName: {
      color: colors.textPrimary,
      fontSize: 14,
      lineHeight: 18,
    },
    activityMeta: {
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 16,
    },
    doneChip: {
      minHeight: 24,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.successBorder,
      backgroundColor: colors.successSurface,
      paddingHorizontal: 8,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 4,
    },
    doneChipText: {
      color: colors.successText,
      fontSize: 11,
      lineHeight: 14,
    },
    pendingChip: {
      minHeight: 24,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 8,
      alignItems: "center",
      justifyContent: "center",
    },
    pendingChipText: {
      color: colors.textMuted,
      fontSize: 11,
      lineHeight: 14,
    },
    emptyBlock: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceSecondary,
      minHeight: 46,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    emptyText: {
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 17,
      textAlign: "center",
    },
    loaderWrap: {
      minHeight: 120,
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    loaderText: {
      color: colors.textSecondary,
      fontSize: 13,
      lineHeight: 18,
    },
  } as const;
}
