import type { AchievementDefinition } from "./types";
import { COMPLETION_MILESTONES } from "./catalogMilestones";

export const PROGRESS_ACHIEVEMENT_DEFINITIONS: readonly AchievementDefinition[] = [
  {
    id: "completions_25",
    title: "25 Completions",
    description: "Complete habits 25 times.",
    tier: "bronze",
    target: COMPLETION_MILESTONES.completions25,
    iconName: "checkbox-multiple-marked",
    resolveProgress: (signals) => signals.totalCompletions,
  },
  {
    id: "completions_100",
    title: "100 Completions",
    description: "Complete habits 100 times.",
    tier: "silver",
    target: COMPLETION_MILESTONES.completions100,
    iconName: "counter",
    resolveProgress: (signals) => signals.totalCompletions,
  },
  {
    id: "completions_300",
    title: "300 Completions",
    description: "Complete habits 300 times.",
    tier: "gold",
    target: COMPLETION_MILESTONES.completions300,
    iconName: "trophy-outline",
    resolveProgress: (signals) => signals.totalCompletions,
  },
  {
    id: "completions_1000",
    title: "1000 Completions",
    description: "Complete habits 1000 times.",
    tier: "legend",
    target: COMPLETION_MILESTONES.completions1000,
    iconName: "crown-outline",
    resolveProgress: (signals) => signals.totalCompletions,
  },
  {
    id: "active_days_7",
    title: "7 Active Days",
    description: "Be active on 7 different days.",
    tier: "bronze",
    target: COMPLETION_MILESTONES.activeDays7,
    iconName: "calendar-heart",
    resolveProgress: (signals) => signals.activeDays,
  },
  {
    id: "active_days_30",
    title: "30 Active Days",
    description: "Be active on 30 different days.",
    tier: "silver",
    target: COMPLETION_MILESTONES.activeDays30,
    iconName: "calendar-month",
    resolveProgress: (signals) => signals.activeDays,
  },
  {
    id: "active_days_90",
    title: "90 Active Days",
    description: "Be active on 90 different days.",
    tier: "gold",
    target: COMPLETION_MILESTONES.activeDays90,
    iconName: "calendar-range",
    resolveProgress: (signals) => signals.activeDays,
  },
  {
    id: "active_days_180",
    title: "180 Active Days",
    description: "Be active on 180 different days.",
    tier: "legend",
    target: COMPLETION_MILESTONES.activeDays180,
    iconName: "calendar-star",
    resolveProgress: (signals) => signals.activeDays,
  },
  {
    id: "perfect_day_5",
    title: "Perfect Day V",
    description: "Finish all scheduled habits in a day 5 times.",
    tier: "silver",
    target: COMPLETION_MILESTONES.perfectDay5,
    iconName: "star-circle-outline",
    resolveProgress: (signals) => signals.perfectDays,
  },
  {
    id: "perfect_day_15",
    title: "Perfect Day XV",
    description: "Finish all scheduled habits in a day 15 times.",
    tier: "gold",
    target: COMPLETION_MILESTONES.perfectDay15,
    iconName: "star-four-points-circle-outline",
    resolveProgress: (signals) => signals.perfectDays,
  },
  {
    id: "perfect_day_50",
    title: "Perfect Day L",
    description: "Finish all scheduled habits in a day 50 times.",
    tier: "legend",
    target: COMPLETION_MILESTONES.perfectDay50,
    iconName: "star-shooting-outline",
    resolveProgress: (signals) => signals.perfectDays,
  },
];
