import type { AchievementDefinition } from "./types";
import { COMPLETION_MILESTONES } from "./catalogMilestones";

export const CORE_ACHIEVEMENT_DEFINITIONS: readonly AchievementDefinition[] = [
  {
    id: "first_habit",
    title: "First Habit",
    description: "Create your first habit.",
    tier: "starter",
    target: COMPLETION_MILESTONES.firstHabit,
    iconName: "sprout",
    resolveProgress: (signals) => signals.totalHabits,
  },
  {
    id: "first_check",
    title: "First Check",
    description: "Complete your first habit check.",
    tier: "starter",
    target: COMPLETION_MILESTONES.firstCheck,
    iconName: "check-decagram",
    resolveProgress: (signals) => signals.totalCompletions,
  },
  {
    id: "first_group",
    title: "First Group",
    description: "Create your first group.",
    tier: "starter",
    target: COMPLETION_MILESTONES.firstGroup,
    iconName: "shape-plus",
    resolveProgress: (signals) => signals.totalGroups,
  },
  {
    id: "first_group_win",
    title: "First Group Win",
    description: "Reach group daily goal for the first time.",
    tier: "starter",
    target: COMPLETION_MILESTONES.firstGroupWin,
    iconName: "bullseye-arrow",
    resolveProgress: (signals) => signals.groupGoalHits,
  },
  {
    id: "perfect_day_1",
    title: "Perfect Day I",
    description: "Finish all scheduled habits in a day once.",
    tier: "starter",
    target: COMPLETION_MILESTONES.perfectDay1,
    iconName: "calendar-check",
    resolveProgress: (signals) => signals.perfectDays,
  },
  {
    id: "streak_3",
    title: "3-Day Streak",
    description: "Reach a 3-day streak.",
    tier: "bronze",
    target: COMPLETION_MILESTONES.streak3,
    iconName: "fire",
    resolveProgress: (signals) => signals.bestStreak,
  },
  {
    id: "streak_7",
    title: "7-Day Streak",
    description: "Reach a 7-day streak.",
    tier: "bronze",
    target: COMPLETION_MILESTONES.streak7,
    iconName: "fire-circle",
    resolveProgress: (signals) => signals.bestStreak,
  },
  {
    id: "streak_21",
    title: "21-Day Streak",
    description: "Reach a 21-day streak.",
    tier: "silver",
    target: COMPLETION_MILESTONES.streak21,
    iconName: "fire-alert",
    resolveProgress: (signals) => signals.bestStreak,
  },
  {
    id: "streak_50",
    title: "50-Day Streak",
    description: "Reach a 50-day streak.",
    tier: "gold",
    target: COMPLETION_MILESTONES.streak50,
    iconName: "firework",
    resolveProgress: (signals) => signals.bestStreak,
  },
  {
    id: "streak_100",
    title: "100-Day Streak",
    description: "Reach a 100-day streak.",
    tier: "legend",
    target: COMPLETION_MILESTONES.streak100,
    iconName: "fireplace",
    resolveProgress: (signals) => signals.bestStreak,
  },
];
